s1, s2, s3, s4, s5, s6, s7 = "True", "False", "1", "0", "NULL", "", " "
print("Float identifiers :")
print("Identifier s1 :", s1, "Type :", type(s1), "ID :", id(s1))
print("Identifier s2 :", s2, "Type :", type(s2), "ID :", id(s2))
print("Identifier s3 :", s3, "Type :", type(s3), "ID :", id(s3))
print("Identifier s4 :", s4, "Type :", type(s4), "ID :", id(s4))
print("Identifier s5 :", s5, "Type :", type(s5), "ID :", id(s5))
print("Identifier s6 :", s6, "Type :", type(s6), "ID :", id(s6))
print("Identifier s7 :", s7, "Type :", type(s7), "ID :", id(s7))
b1 = bool(s1)
b2 = bool(s2)
b3 = bool(s3)
b4 = bool(s4)
b5 = bool(s5)
b6 = bool(s6)
b7 = bool(s7)
print("\nString identifiers converted into Boolean type :")
print("Identifier b1 :", b1, "Type :", type(b1), "ID :", id(b1))
print("Identifier b2 :", b2, "Type :", type(b2), "ID :", id(b2))
print("Identifier b3 :", b3, "Type :", type(b3), "ID :", id(b3))
print("Identifier b4 :", b4, "Type :", type(b4), "ID :", id(b4))
print("Identifier b5 :", b5, "Type :", type(b5), "ID :", id(b5))
print("Identifier b6 :", b6, "Type :", type(b6), "ID :", id(b6))
print("Identifier b7 :", b7, "Type :", type(b7), "ID :", id(b7))
print("\nThank you.")
